# frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:
    app: frontend
    tier: web
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      tier: web
      project: expense
  template:
    metadata:
      labels:
        app: frontend
        tier: web
        project: expense
    spec:
      containers:
      - name: frontend
        image: srinivasdevops97/frontend:v1
---
# backend Service
kind: Service
apiVersion: v1
metadata:
  name: frontend  # name of the service
  namespace: expense
spec:
  type: LoadBalancer
  selector:
    app: frontend
    tier: web
    project: expense
  ports:       # list of the ports
  - name: frontend-port
    protocol: TCP
    port: 80   # service port
    targetPort: 80     # container port(another port)
